[project]
name = "code_automation"
version = "0.1.0"
description = "code-automation using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.117.1,<1.0.0"
]

[project.scripts]
code_automation = "code_automation.main:run"
run_crew = "code_automation.main:run"
train = "code_automation.main:train"
replay = "code_automation.main:replay"
test = "code_automation.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
