software_thinking_task:
  description: >
    Generate three distinct and innovative software project ideas about {topic} 
    that a solo developer could realistically build within 1 to 2 weeks.
    Briefly explain the core functionality and potential user benefit of each idea.
  expected_output: >
    A markdown file containing the list of ideas
    Markdown file location : {ideas_file_path}

solution_architect_task:
  description: >
    Read the project ideas from {ideas_file_path} and design a detailed implementation plan for each of them. 
    Break down features, decide on technologies, and outline a rough system architecture.
    Write the plan in separate markdown file for each idea.
  expected_output: >
    Separate markdown files containing individal plan for an idea.
    Save the file for an idea at specified location with name of the idea and .md extension
    Markdown file location : {plan_files_folder}
